# Site settings
title: Alex Vargas
email: vargas.84@osu.edu
description: > # this means to ignore newlines until "baseurl:"
  An overview/showcase of the work, experience and sometimes thoughts of Alex
  Vargas (proud father, hacker and student).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  vargas84

# Build settings
markdown: kramdown
